services:
  db:
    image: leoof/tecnomundo-database:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=superPassword@root
      - MYSQL_USER=userAdmin
      - MYSQL_PASSWORD=pwdAdmin@tecno_mundo
    ports:
      - '3307:3306'
    networks:
      - backend
    container_name: 'mysql_container'
    volumes:
      - 'db_data:/var/lib/mysql'
    command:
      - --ssl=0


  rabbit_mq:
    image: leoof/tecnomundo-rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend


  identity:
    image: leoof/tecnomundo-identity-server:v1
    container_name: "identity"
    build:
      context: TecnoMundo.IdentityAPI
    depends_on:
      - db
    ports:
      - '4435:8080'
    restart: always
    networks:
      - backend
    environment:
      - MySQLConnection__MySQLConnectionString=Server=db;DataBase=tecno_mundo_identity_api;Uid=root;Pwd=superPassword@root;
    
  
  product:
    image: leoof/tecnomundo-product:v1
    container_name: "product"
    build:
      context: TecnoMundo.ProductAPI
    depends_on:
      - db
      - identity
    ports:
      - '4440:8080'
    environment:
      - MySQLConnection__MySQLConnectionString=Server=db;DataBase=tecno_mundo_product_api;Uid=root;Pwd=superPassword@root;
    restart: always
    networks:
      - backend
  

  coupon:
    image: leoof/tecnomundo-coupon:v1
    container_name: "coupon"
    build:
      context: TecnoMundo.CouponAPI
    depends_on:
      - db
      - identity
    ports:
      - '4445:8080'
    restart: always
    environment:
      - MySQLConnection__MySQLConnectionString=Server=db;DataBase=tecno_mundo_coupon_api;Uid=root;Pwd=superPassword@root;
    networks:
      - backend
  

  cart:
    image: leoof/tecnomundo-cart:v1
    container_name: 'cart'
    build: 
      context: 'TecnoMundo.CartAPI'
    depends_on:
      - product
      - db
      - coupon
      - rabbit_mq
    ports:
      - '4450:8080'
    restart: always
    environment:
      - MySQLConnection__MySQLConnectionString=Server=db;DataBase=tecno_mundo_cart_api;Uid=root;Pwd=superPassword@root;
      - RabbitMQServer__HostName=rabbit_mq
      - RabbitMQServer__Password=guest
      - RabbitMQServer__Username=guest
      - ServiceUrls__ProductAPI=http://product:8080
    networks:
      - backend
  

  payment:
    image: leoof/tecnomundo-payment:v1
    container_name: 'payment'
    restart: always
    build: 
      context: 'TecnoMundo.PaymentAPI'
    depends_on:
      - rabbit_mq
    environment:
      - RabbitMQServer__HostName=rabbit_mq
      - RabbitMQServer__Password=guest
      - RabbitMQServer__Username=guest
    networks:
      - backend
  

  order:
    image: leoof/tecnomundo-order:v1
    container_name: 'order'
    restart: always
    build: 
      context: 'TecnoMundo.OrderAPI'
    depends_on:
      - rabbit_mq
      - db
      - identity
    environment:
      - MySQLConnection__MySQLConnectionString=Server=db;DataBase=tecno_mundo_order_api;Uid=root;Pwd=superPassword@root;
      - RabbitMQServer__HostName=rabbit_mq
      - RabbitMQServer__Password=guest
      - RabbitMQServer__Username=guest
    networks:
      - backend


volumes:
  db_data:


networks:
  backend: