services:
  # Pode descomentar para rodar localmente e algumas informações devem ser passadas para as API's
  # db:
  #   container_name: 'mysql_container'
  #   image: leoof/tecnomundo-database:latest
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=superPassword@root
  #   ports:
  #     - '3307:3306'
  #   networks:
  #     - backend


  identity:
    image: leoof/tecnomundo-identity-server:latest
    container_name: "identity"
    build:
      context: TecnoMundo.IdentityAPI
    ports:
      - '4435:8080'
    restart: always
    networks:
      - backend
    environment:
      - AuthenticationSettings__Secret=${TOKEN_KEY}
      - AuthenticationSettings__ExpiressHours=${TOKEN_EXPIRE}
      - AuthenticationSettings__AudienceToken=${TOKEN_AUDIENCE}
      - AuthenticationSettings__ProvaiderToken=${TOKEN_PROVAIDER}
      - CorsPolicy__TecnoMundo-Web-Http=http://${ENV_HOST}
      - CorsPolicy__TecnoMundo-Web-Https=https://${ENV_HOST}
      - MySQLConnection__MySQLConnectionString=Server=${DB_SERVER};DataBase=tecno_mundo_identity_api;Uid=${DB_USER};Pwd=${DB_PASSWORD};
    
  
  product:
    image: leoof/tecnomundo-product:latest
    container_name: "product"
    build:
      context: TecnoMundo.ProductAPI
    ports:
      - '4440:8080'
    environment:
      - Authentication__Key=${TOKEN_KEY}
      - CorsPolicy__TecnoMundo-Web-Http=http://${ENV_HOST}
      - CorsPolicy__TecnoMundo-Web-Https=https://${ENV_HOST}
      - MySQLConnection__MySQLConnectionString=Server=${DB_SERVER};Port=3306;DataBase=tecno_mundo_product_api;Uid=${DB_USER};Pwd=${DB_PASSWORD};
    restart: always
    networks:
      - backend
  

  coupon:
    image: leoof/tecnomundo-coupon:latest
    container_name: "coupon"
    build:
      context: TecnoMundo.CouponAPI
    ports:
      - '4445:8080'
    restart: always
    environment:
      - Authentication__Key=${TOKEN_KEY}
      - Authentication__UrlAuthentication=${TOKEN_PROVAIDER}
      - Authentication__Scope=${TOKEN_AUDIENCE}
      - CorsPolicy__TecnoMundo-Web-Http=http://${ENV_HOST}
      - CorsPolicy__TecnoMundo-Web-Https=https://${ENV_HOST}
      - MySQLConnection__MySQLConnectionString=Server=${DB_SERVER};DataBase=tecno_mundo_coupon_api;Uid=${DB_USER};Pwd=${DB_PASSWORD};
    networks:
      - backend
  

  cart:
    image: leoof/tecnomundo-cart:latest
    container_name: 'cart'
    build: 
      context: 'TecnoMundo.CartAPI'
    depends_on:
      - product
      - coupon
    ports:
      - '4450:8080'
    restart: always
    environment:
      - Authentication__Key=${TOKEN_KEY}
      - Authentication__UrlAuthentication=${TOKEN_PROVAIDER}
      - Authentication__Scope=${TOKEN_AUDIENCE}
      - ServiceUrls__ProductAPI=http://product:8080
      - ServiceUrls__CouponAPI=http://coupon:8080
      - RabbitMQServer__HostName=${RABBITMQ_HOSTNAME}
      - RabbitMQServer__Password=${RABBITMQ_PASSWORD}
      - RabbitMQServer__Username=${RABBITMQ_USERNAME}
      - RabbitMQServer__VirtualHost=${RABBITMQ_VIRTUAL_HOST}
      - CorsPolicy__TecnoMundo-Web-Http=http://${ENV_HOST}
      - CorsPolicy__TecnoMundo-Web-Https=https://${ENV_HOST}
      - MySQLConnection__MySQLConnectionString=Server=${DB_SERVER};DataBase=tecno_mundo_cart_api;Uid=${DB_USER};Pwd=${DB_PASSWORD};
    networks:
      - backend
  

  payment:
    image: leoof/tecnomundo-payment:latest
    container_name: 'payment'
    restart: always
    build: 
      context: 'TecnoMundo.PaymentAPI'
    environment:
      - Authentication__Key=${TOKEN_KEY}
      - RabbitMQServer__HostName=${RABBITMQ_HOSTNAME}
      - RabbitMQServer__Password=${RABBITMQ_PASSWORD}
      - RabbitMQServer__Username=${RABBITMQ_USERNAME}
      - RabbitMQServer__VirtualHost=${RABBITMQ_VIRTUAL_HOST}
    networks:
      - backend
  

  order:
    image: leoof/tecnomundo-order:latest
    container_name: 'order'
    restart: always
    build: 
      context: 'TecnoMundo.OrderAPI'
    ports:
      - '4455:8080'
    environment:
      - Authentication__Key=${TOKEN_KEY}
      - Authentication__UrlAuthentication=${TOKEN_PROVAIDER}
      - Authentication__Scope=${TOKEN_AUDIENCE}
      - RabbitMQServer__HostName=${RABBITMQ_HOSTNAME}
      - RabbitMQServer__Password=${RABBITMQ_PASSWORD}
      - RabbitMQServer__Username=${RABBITMQ_USERNAME}
      - RabbitMQServer__VirtualHost=${RABBITMQ_VIRTUAL_HOST}
      - CorsPolicy__TecnoMundo-Web-Http=http://${ENV_HOST}
      - CorsPolicy__TecnoMundo-Web-Https=https://${ENV_HOST}
      - MySQLConnection__MySQLConnectionString=Server=${DB_SERVER};DataBase=tecno_mundo_order_api;Uid=${DB_USER};Pwd=${DB_PASSWORD};
    networks:
      - backend
  

  page:
    image: leoof/tecnomundo-web:latest
    container_name: 'page'
    restart: always
    build: 
      context: 'TecnoMundo.Web'
    ports:
      - '80:80'
      - '443:80'
    environment:
      - BASE_API_URL_PRODUCT=http://${ENV_HOST}:4440/api/latest/Product/
      - BASE_API_URL_IDENTITY=http://${ENV_HOST}:4435/api/latest/Authentication/
      - BASE_API_URL_CART=http://${ENV_HOST}:4450/api/latest/Cart/
      - BASE_API_URL_COUPON=http://${ENV_HOST}:4445/api/latest/Coupon/
      - BASE_API_URL_ORDER=http://${ENV_HOST}:4455/api/latest/Order/


volumes:
  db_data:


networks:
  backend:
